apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    note: generated
  disableNameSuffixHash: true
  labels:
    type: generated

secretGenerator:
- name: gitolite-sshd
  files:
  - ssh/sshd_config

resources:
 - service.yaml
 - statefulset.yaml
 - persistentVolumeClaim.yaml
