apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitolite-data
spec:
  selector:
    matchLabels:
      app: gitolite
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
