apiVersion: v1
kind: Service
metadata:
  name: gitolite-sshd
  labels:
    app: gitolite
spec:
  ports:
  - name: sshd
    port: 2222
    protocol: TCP
  selector:
    app: gitolite
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 10.0.0.1
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ipFamilyPolicy: PreferDualStack
  internalTrafficPolicy: Cluster
